spring:
  redis:
    host: local.redis.com
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://local.mysql.com:3306/cloud_oauth?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  mvc:
    servlet:
      load-on-startup: 1
access_token:
  store-jwt: false
logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
security:
  oauth2:
    resource:
      filter-order: 3
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  eager-load:
    enabled: true
    clients: user-center