logging:
  level:
    root: info
    com.cloud: debug
  file: /spring-cloud/logs/${spring.application.name}.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.170:3306/cloud_backend?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: c++java123
  rabbitmq:
    host: 192.168.1.170
    port: 5672
    username: cloud-dev
    password: cloud-dev
    virtual-host: /
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username:
    password:
    protocol: smtp
    test-connection: false
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
mybatis:
  type-aliases-package: com.cloud.backend.model,com.cloud.model.mail
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
security:
  oauth2:
    resource:
      user-info-uri: http://192.168.1.170:8080/api-o/user-me
      prefer-token-info: false